### ISSUE TITLE
Reduce compilation time of visitors

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/nmodl#298] opened 2020-04-16 10:16 UTC
## Target

We can speed up the compilation time by:
1. avoid including `ast/ast.hpp` when not necessary. For instance visitor class declaration should only use forward declarations
1. most visitors only visit a sub-set of the AST nodes. Therefore, visitor class definitions in .cpp should only include the AST nodes required.

## Proposal

* First point can be easily changed, actually I have a branch where it is already done.
* Second point requires more changes:
  * generate one C++ header per AST class. nmodl.yaml should already contain the necessary information to build the AST nodes inter-dependencies to create the proper `#include <ast/ast_XXX.hpp>` directives on-top of each header file.
   * There is no need to split ast.cpp.
   * Update ast.hpp to either:
     1.include all ast_XXX.hpp headers but it will increase the amount of I/O 
     2. duplicate the content in `ast.hpp` but add preprocessor fences to prevent a class to be declared twice if a C++ file includes both ast.hpp and ast_xxx.hpp. _This is my favorite option_

**Comment by cattabiani** [comment] 2020-04-16 12:15
First point: no problemo, +1
Second point: it could be done. However, auto-generate the includes could lead to compilation errors. Easy to debug but potentially high in number. I am not sure how much faster the compilation would be. I should look more closely into this topic

**Comment by ohm314** [comment] 2020-04-16 13:53
I like your proposal @tristan0x ! Regarding the last point, I think 2. will be the better solution even though I dislike preproc fences.

**Comment by ohm314** [comment] 2020-04-16 13:57
@cattabiani I think compilation will be substantially faster, also the IDE does not choke anymore on the big headers being included. The auto-generation of the `ast_XXX.hpp` files should be not a problem at all, the code is already generated correctly, now it should just go into a new file for each class. Most dependencies between ast class declarations can be done with fwd declarations too, no?

**Comment by pramodk** [comment] 2020-04-16 14:01
I will post some details in the evening but it would be worth looking at pyast and see if it’s only header size or something else (e.g. pybind11).

I am mentioning this because I never noticed the issue with cpp compilation but as soon as pybind stuff comes in, it causes the problem.

(we should definitely reduce the header size for sure but just pointing out the issue that has caused this discussion ).

**Comment by pramodk** [comment] 2020-04-16 23:02
Spent some time to look into root cause, see #299 and summary/conclusion.

> First point can be easily changed, actually I have a branch where it is already done.

👍 straightforward.

> generate one C++ header per AST class. nmodl.yaml should already contain the necessary information to build the AST nodes inter-dependencies to create the proper #include <ast/ast_XXX.hpp> directives on-top of each header file.

I see the principal `include-what-you-use` but at the same time bit hesitant as well because

1. if some visitor is using 15-20 AST classes, we need to have 15-20 includes.
2. the major bottleneck is coming from pyast.cpp and pyvisitor.cpp. These are Jinja generated files. If we can split these two files into smaller pieces, we can solve 80% of current frustration. And this change is self contained and small enough that won't require global changes.

So, to start with we can first target point 2 (i.e. splitting pyast.cpp and pyvisitor.cpp) and then come back to splitting `ast.hpp` by bit more analysis on overall improvements/drawbacks?

**Comment by alkino** [comment] 2023-03-24 00:09
today ast.hpp is split, so should we close it?

**Closed** 2023-03-24 15:45 UTC
Labels: enhancement, ast, refactoring, proposal
