### ISSUE TITLE
Segmentation fault while translating hh.mod in CoreNEURON CI (Intel compiler)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#731] opened 2021-09-06 21:18 UTC
CoreNEURON CI is failing https://github.com/BlueBrain/CoreNeuron/pull/624 with the following error:

```console
$ /gpfs/bbp.cscs.ch/ssd/gitlab_map_jobs/bbpcihpcproj12/P15931/55181/spack/opt/spack/linux-rhel7-x86_64/intel-19.1.2.254/nmodl-develop-lqyttq/bin/nmodl \
        x86_64/corenrn/mod2c/hh.mod \
       -o x86_64/corenrn/mod2c/ host \
       --c passes --inline codegen --force
[NMODL] [info] :: Processing x86_64/corenrn/mod2c/hh.mod
[NMODL] [info] :: Running symtab visitor
[NMODL] [info] :: Running CVode to cnexp visitor
[NMODL] [info] :: Running LOCAL to ASSIGNED visitor
[NMODL] [info] :: Running code compatibility checker
[NMODL] [info] :: Running verbatim rename visitor
[NMODL] [info] :: Running KINETIC block visitor
[NMODL] [info] :: Running STEADYSTATE visitor
[NMODL] [info] :: Parsing Units
[NMODL] [info] :: Running nmodl inline visitor
[NMODL] [warning] :: RenameVisitor :: Renaming variable vtrap at 119.17-21 to vtrap_in_0
[NMODL] [warning] :: RenameVisitor :: Renaming variable vtrap at 121.17-21 to vtrap_in_0
Segmentation fault
```

**Comment by pramodk** [comment] 2021-09-07 11:07
See the discussion in https://github.com/BlueBrain/CoreNeuron/pull/631. As 1) CI passes without ccache 2) can't reproduce the error on BB5 3) valgrind doesn't show anything obvious, I suspect the issue is with `ccache` somehow?
Something to discuss when Olli will be back.

**Comment by olupton** [comment] 2021-09-13 14:15
I can't reproduce this error, and the working directory from the old test has been cleaned up.

I ran the CoreNEURON pipeline several times with/without `ccache` re-enabled (https://github.com/BlueBrain/CoreNeuron/commit/41338243da14d00d51312e4179658968d4310f05) and did not see any problem. Internal reference of pipelines: [#16278](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16278) [#16294](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16294) [#16303](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16303) [#16304](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16304) [#16334](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16334) [#16335](https://bbpgitlab.epfl.ch/hpc/coreneuron/-/pipelines/16335).

Closing this; it can be reopened if we manage to reproduce the problem again.

**Closed by olupton** 2021-09-13 14:15 UTC
Labels: bug, codegen
